version: '3.8'

# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

services:
  app:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development
    volumes:
      # Enable hot reloading in development
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./public:/opt/app/public
      - ./package.json:/opt/app/package.json
      - ./tsconfig.json:/opt/app/tsconfig.json
      - /opt/app/node_modules
    command: ["npm", "run", "develop"]
    ports:
      - "1337:1337"

  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mechanico_cms_dev